# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "03cccdd9479bd45fe02e377e43b8c3b5"
name = "Cascade"
application_url = "https://cascade-app-off6g.ondigitalocean.app"
embedded = true

[access_scopes]
scopes = "read_products,write_products,read_inventory,write_inventory,read_content,write_content,read_online_store_navigation,write_online_store_navigation,read_files,write_files"
use_legacy_install_flow = false

[auth]
redirect_urls = ["https://cascade-app-off6g.ondigitalocean.app/auth/callback"]

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
topics = ["app/uninstalled", "app/scopes_update"]
compliance_topics = ["customers/redact", "customers/data_request", "shop/redact"]
uri = "/webhooks"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "steadro-dev-2.myshopify.com"
